# Generated by Django 5.0.6 on 2024-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
